package com.transcriptextractor.yttranscriptextractor.service;

import com.transcriptextractor.yttranscriptextractor.model.TranscriptResponse;
import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Value;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

@Service
public class YoutubeService {

    private final YouTubeAPIService youtubeAPIService;

    @Value("${youtube.api.key}")
    private String apiKey;

    //Cache to avoid repeated API calls
    private final Map<String, String> transcriptCache = new HashMap<>();

    public YoutubeService(YouTubeAPIService youtubeAPIService) {
        this.youtubeAPIService = youtubeAPIService;
    }

    public TranscriptResponse extractTranscript(String videoUrl) {
        try {
            String videoId = extractVideoId(videoUrl);
            if (videoId == null || videoId.isEmpty()) {
                return new TranscriptResponse("Invalid YouTube URL. Please check the URL and try again.");
            }

            //Check cache first
            if (transcriptCache.containsKey(videoId)) {
                return createCachedResponse(videoId);
            }

            // Get video details from YouTube API
            Map<String, Object> videoDetails = youtubeAPIService.getVideoDetails(videoId);

            // Extract video information
            String title = extractVideoTitle(videoDetails);
            String channelTitle = extractChannelTitle(videoDetails);
            String description = extractDescription(videoDetails);
            String thumbnailUrl = extractThumbnailUrl(videoDetails);
            String duration = extractDuration(videoDetails);
            String publishedAt = extractPublishedAt(videoDetails);

            // Try to get transcript using different methods
            String transcript = null;
            String warning = null;

            // Method 1: Try to get from auto-generated captions (if available)
            transcript = extractAutoGeneratedCaptions(videoId);

            // Method 2: If no auto-captions, try to parse from description/community posts
            if (transcript == null || transcript.isEmpty()) {
                transcript = extractFromDescription(description);
                if (transcript != null) {
                    warning = "Note: Transcript extracted from video description (may be incomplete)";
                }
            }

            // Method 3: If still no transcript, check for community posts
            if (transcript == null || transcript.isEmpty()) {
                transcript = checkCommunityPosts(videoId);
                if (transcript != null) {
                    warning = "Note: Transcript extracted from community posts";
                }
            }

            // Method 4: Last resort - provide video details
            if (transcript == null || transcript.isEmpty()) {
                transcript = generateVideoSummary(videoDetails);
                warning = "Note: No transcript available. Showing video summary instead.";
            }

            // Create response
            TranscriptResponse response = new TranscriptResponse(transcript, videoId, title);
            response.setChannelTitle(channelTitle);
            response.setDescription(description);
            response.setThumbnailUrl(thumbnailUrl);
            response.setDuration(duration);
            response.setPublishedAt(publishedAt);
            response.setWarning(warning);

            // Add structured captions if available
            List<TranscriptResponse.Caption> captions = parseStructuredCaptions(transcript);
            if (!captions.isEmpty()) {
                response.setCaptions(captions);
            }

            return response;

        } catch (Exception e) {
            return new TranscriptResponse("Error extracting transcript: " + e.getMessage());
        }
    }

    private String extractVideoId(String url) {
        try {
            String regex = "(?:youtube\\.com\\/watch\\?v=|youtu\\.be\\/|youtube\\.com\\/embed\\/|youtube\\.com\\/v\\/|youtube\\.com\\/e\\/|youtu\\.be\\/|youtube\\.com\\/watch\\?.*v=|youtube\\.com\\/.*[\\?&]v=)([^#&?\\n<>]*)";
            Pattern pattern = Pattern.compile(regex, Pattern.CASE_INSENSITIVE);
            Matcher matcher = pattern.matcher(url);

            if (matcher.find()) {
                return matcher.group(1);
            }
            return null;
        } catch (Exception e) {
            return null;
        }
    }

    private String extractVideoTitle(Map<String, Object> videoDetails) {
        try {
            Map<String, Object> items = getItems(videoDetails);
            if (items != null) {
                Map<String, Object> snippet = (Map<String, Object>) items.get("snippet");
                if (snippet != null) {
                    return (String) snippet.get("title");
                }
            }
        } catch (Exception e) {
            // Fall through
        }
        return "Unknown Title";
    }

    private String extractChannelTitle(Map<String, Object> videoDetails) {
        try {
            Map<String, Object> items = getItems(videoDetails);
            if (items != null) {
                Map<String, Object> snippet = (Map<String, Object>) items.get("snippet");
                if (snippet != null) {
                    return (String) snippet.get("channelTitle");
                }
            }
        } catch (Exception e) {
            // Fall through
        }
        return "Unknown Channel";
    }

    private String extractDescription(Map<String, Object> videoDetails) {
        try {
            Map<String, Object> items = getItems(videoDetails);
            if (items != null) {
                Map<String, Object> snippet = (Map<String, Object>) items.get("snippet");
                if (snippet != null) {
                    return (String) snippet.get("description");
                }
            }
        } catch (Exception e) {
            // Fall through
        }
        return "";
    }

    private String extractThumbnailUrl(Map<String, Object> videoDetails) {
        try {
            Map<String, Object> items = getItems(videoDetails);
            if (items != null) {
                Map<String, Object> snippet = (Map<String, Object>) items.get("snippet");
                if (snippet != null) {
                    Map<String, Object> thumbnails = (Map<String, Object>) snippet.get("thumbnails");
                    if (thumbnails != null) {
                        Map<String, Object> highRes = (Map<String, Object>) thumbnails.get("high");
                        if (highRes != null) {
                            return (String) highRes.get("url");
                        }
                    }
                }
            }
        } catch (Exception e) {
            // Fall through
        }
        return "";
    }

    private String extractDuration(Map<String, Object> videoDetails) {
        try {
            Map<String, Object> items = getItems(videoDetails);
            if (items != null) {
                Map<String, Object> contentDetails = (Map<String, Object>) items.get("contentDetails");
                if (contentDetails != null) {
                    return (String) contentDetails.get("duration");
                }
            }
        } catch (Exception e) {
            // Fall through
        }
        return "";
    }

    private String extractPublishedAt(Map<String, Object> videoDetails) {
        try {
            Map<String, Object> items = getItems(videoDetails);
            if (items != null) {
                Map<String, Object> snippet = (Map<String, Object>) items.get("snippet");
                if (snippet != null) {
                    return (String) snippet.get("publishedAt");
                }
            }
        } catch (Exception e) {
            // Fall through
        }
        return "";
    }

    @SuppressWarnings("unchecked")
    private Map<String, Object> getItems(Map<String, Object> response) {
        List<Map<String, Object>> items = (List<Map<String, Object>>) response.get("items");
        if (items != null && !items.isEmpty()) {
            return items.get(0);
        }
        return null;
    }

    /**
     * Extract auto-generated captions (this requires additional permissions)
     * Note: YouTube Data API v3 requires OAuth 2.0 for caption downloads
     */
    private String extractAutoGeneratedCaptions(String videoId) {
        try {
            // This is a simplified version. Actual implementation requires:
            // 1. OAuth 2.0 authentication
            // 2. Captions().download() method

            // For now, we'll check if captions exist
            Map<String, Object> captions = youtubeAPIService.getVideoCaptions(videoId);
            if (captions != null && captions.containsKey("items")) {
                List<Map<String, Object>> items = (List<Map<String, Object>>) captions.get("items");
                if (items != null && !items.isEmpty()) {
                    return "Auto-generated captions are available for this video.\n" +
                            "Note: Full transcript download requires additional permissions.";
                }
            }

            return null;
        } catch (Exception e) {
            return null;
        }
    }

    /**
     * Extract transcript-like content from video description
     */
    private String extractFromDescription(String description) {
        if (description == null || description.isEmpty()) {
            return null;
        }

        // Look for common transcript patterns in description
        String[] transcriptIndicators = {
                "0:00", "0:", "1:", "2:", "3:", "4:", "5:",
                "CHAPTERS", "TIMESTAMPS", "TRANSCRIPT",
                "Introduction", "Conclusion", "Summary"
        };

        for (String indicator : transcriptIndicators) {
            if (description.contains(indicator)) {
                // Clean up the description
                String cleaned = description.replaceAll("(?m)^[\\s\\t]*\\n", "")
                        .replaceAll("\\n{3,}", "\n\n");
                return "Extracted from video description:\n\n" + cleaned;
            }
        }

        return null;
    }

    /**
     * Check community posts for transcripts
     * Note: This is a placeholder - actual implementation would require
     * additional API calls and permissions
     */
    private String checkCommunityPosts(String videoId) {
        // Community posts API requires additional permissions
        // and is not available in basic YouTube Data API v3
        return null;
    }

    /**
     * Generate a summary from video details when no transcript is available
     */
    private String generateVideoSummary(Map<String, Object> videoDetails) {
        StringBuilder summary = new StringBuilder();

        String title = extractVideoTitle(videoDetails);
        String channel = extractChannelTitle(videoDetails);
        String description = extractDescription(videoDetails);

        summary.append("📹 Video Summary\n");
        summary.append("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n");
        summary.append("Title: ").append(title).append("\n");
        summary.append("Channel: ").append(channel).append("\n\n");

        if (description != null && !description.isEmpty()) {
            // Take first 500 characters of description
            String shortDesc = description.length() > 500 ?
                    description.substring(0, 500) + "..." : description;
            summary.append("Description:\n").append(shortDesc).append("\n\n");
        }

        summary.append("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n");
        summary.append("ℹ️  Transcript Unavailable\n\n");
        summary.append("This video doesn't have publicly available transcripts.\n");
        summary.append("Possible reasons:\n");
        summary.append("• Creator hasn't added captions\n");
        summary.append("• Auto-generated captions are disabled\n");
        summary.append("• Transcript requires additional permissions\n\n");
        summary.append("Try videos that have CC (Closed Captions) enabled.");

        return summary.toString();
    }

    /**
     * Parse transcript into structured captions with timestamps
     */
    private List<TranscriptResponse.Caption> parseStructuredCaptions(String transcript) {
        List<TranscriptResponse.Caption> captions = new ArrayList<>();

        if (transcript == null || transcript.isEmpty()) {
            return captions;
        }

        // Look for timestamp patterns
        Pattern timestampPattern = Pattern.compile("(\\d{1,2}:\\d{2}:\\d{2}|\\d{1,2}:\\d{2})\\s*(.*?)(?=\\n\\d{1,2}:|\\n\\n|$)");
        Matcher matcher = timestampPattern.matcher(transcript);

        while (matcher.find()) {
            String timestamp = matcher.group(1);
            String text = matcher.group(2).trim();

            if (!text.isEmpty()) {
                captions.add(new TranscriptResponse.Caption(text, timestamp, ""));
            }
        }

        // If no timestamps found, split by lines
        if (captions.isEmpty()) {
            String[] lines = transcript.split("\\n");
            for (int i = 0; i < lines.length; i++) {
                String line = lines[i].trim();
                if (!line.isEmpty()) {
                    captions.add(new TranscriptResponse.Caption(line, String.format("%d:00", i), ""));
                }
            }
        }

        return captions;
    }

    /**
     * Alternative: Use external transcript service as fallback
     */
    private String fetchFromExternalService(String videoId) {
        try {
            // Example using a public transcript API (requires API key)
            String rapidApiKey = System.getenv("RAPIDAPI_KEY");
            if (rapidApiKey != null && !rapidApiKey.isEmpty()) {
                String url = "https://youtube-transcriptor.p.rapidapi.com/transcript?video_id=" + videoId;

                HttpURLConnection conn = (HttpURLConnection) new URL(url).openConnection();
                conn.setRequestMethod("GET");
                conn.setRequestProperty("X-RapidAPI-Key", rapidApiKey);
                conn.setRequestProperty("X-RapidAPI-Host", "youtube-transcriptor.p.rapidapi.com");

                if (conn.getResponseCode() == 200) {
                    BufferedReader reader = new BufferedReader(new InputStreamReader(conn.getInputStream()));
                    StringBuilder response = new StringBuilder();
                    String line;
                    while ((line = reader.readLine()) != null) {
                        response.append(line);
                    }
                    reader.close();

                    // Parse JSON response
                    // This is simplified - you'd need to parse the actual JSON structure
                    return response.toString();
                }
            }
        } catch (Exception e) {
            // Silent fail - external service is optional
        }
        return null;
    }
}